### ISSUE TITLE
Scale of the log window seems wrong

### ISSUE THREAD

**Issue by ProgrammerFailure** [ihsoft/KSPDev_LogConsole#12]
I have this mod installed, and when I open the log console, this is what it looks like:  
![image](https://github.com/ihsoft/KSPDev_LogConsole/assets/122328786/bedb00c9-28cd-4d14-8aa6-bc3ae00e96c2)

That makes it difficult to see everything in the console window. How can I resize it?

**Comment by ihsoft** [comment]
Which screen resolution do you have? T ofix the size, try clikcing the arrows at the top left.

**Comment by ProgrammerFailure** [comment]
Hello, for some reason waking my computer from sleep fixed the issue...
Also, is there a way to add other log sources to your console window? Specifically the MMPatch file in "<KSP root>/PluginData/ModuleManager"

**Comment by ihsoft** [comment]
No sure I get the last request. The LogConsole shows all the logs that Unit gets. However, the mod is not loaded immediately, so it cannot capture the very early records when the game is loading.

**Comment by ihsoft** [comment]
Or wait. Did you mean the "source" in the logs records? If so, you can adjust it via the config here: https://github.com/ihsoft/KSPDev_LogConsole/blob/master/settings.cfg#L72.

Just add a prefix or exact source name up to which you _don't want_ to see the source. If the matching record is found in the stack trace, then everything before will be skipped. E.g. if the stack was:

```
source.which.i-want
stuff.i-hate.1
stuff.i-hate.2
stuff.i-hate.3
some.other.stuff
more.other.stuff
```

Then, by setting `PrefixMatchOverride = stuff.i-hate.` you skip everything up to `source.which.i-want`. And this will be the source you will see in the logs. Checkout what's already there in the file. THis is how the console skips unrelated stuff.

I'm not playing KSP for a pretty long time already, so I'm not aware of the current trends.
