### ISSUE TITLE
Quick Filter to Quick Search

### ISSUE THREAD

**Issue by yalov** [ihsoft/KSPDev_LogConsole#7]
filter by a mod name for mods what add its name as a log output prefix

**Comment by ihsoft** [comment]
Not sure if I get it. Could you , pelase, give some examples?

**Comment by yalov** [comment]
Showing Log-info-output only for some target mod can be very helpful for debugging the mod.

if mod add Prefix with its name it cab=n be used for filtering

**Comment by ihsoft** [comment]
That's the reason why we have "quick filter". Are you saying we need an ability to "quick filter" multiple of mods?

**Comment by yalov** [comment]
then it looks like that "quick filter" doesn't work

**Comment by ihsoft** [comment]
And that's where we need an exact example. When I type "kas" into the quick filter dialog, I see exactly what I need - the KAS logs. Could you, please, give your example?

**Comment by yalov** [comment]
unfiltered:
![](https://i.imgur.com/PHko8Jz.png)

typed "USKAM", pressed Enter
![](https://i.imgur.com/d7hA8NT.png)

**Comment by ihsoft** [comment]
Hmm. It sounds like you've installed the mod incorrectly. The `UnityEngine.Application.CallLogCallback` call is known to be system, and it's ignored by the the stock config. Check if you have the right file at `GameData\KSPDev\LogConsole\Plugins\PluginData\settings.cfg`.

**Comment by yalov** [comment]
I see, I copied without KSPDev to GameData\LogConsole.
It works now
